import type { IsometricCleaningMessItem } from '../types/isometricRoom';

export const isometricCleaningMessSafeArea = {
  minX: 150,
  maxX: 520,
  minY: 318,
  maxY: 432,
};

export const isometricCleaningMessItems: IsometricCleaningMessItem[] = [
  {
    id: 'mess-paper-01',
    type: 'paper',
    x: 238,
    y: 340,
    width: 18,
    height: 12,
    rotation: '-13deg',
    visibleUntilStage: 1,
    zIndex: 67,
  },
  {
    id: 'mess-paper-02',
    type: 'paper',
    x: 354,
    y: 374,
    width: 20,
    height: 13,
    rotation: '11deg',
    visibleUntilStage: 2,
    zIndex: 68,
  },
  {
    id: 'mess-paper-03',
    type: 'paper',
    x: 452,
    y: 326,
    width: 15,
    height: 11,
    rotation: '-6deg',
    visibleUntilStage: 3,
    zIndex: 68,
  },
  {
    id: 'mess-dust-01',
    type: 'dust',
    x: 210,
    y: 370,
    width: 28,
    height: 10,
    rotation: '-8deg',
    visibleUntilStage: 2,
    zIndex: 66,
  },
  {
    id: 'mess-dust-02',
    type: 'dust',
    x: 302,
    y: 392,
    width: 35,
    height: 12,
    rotation: '7deg',
    visibleUntilStage: 3,
    zIndex: 66,
  },
  {
    id: 'mess-dust-03',
    type: 'dust',
    x: 424,
    y: 382,
    width: 31,
    height: 11,
    rotation: '-5deg',
    visibleUntilStage: 2,
    zIndex: 66,
  },
  {
    id: 'mess-dust-04',
    type: 'dust',
    x: 488,
    y: 348,
    width: 26,
    height: 9,
    rotation: '13deg',
    visibleUntilStage: 1,
    zIndex: 66,
  },
  {
    id: 'mess-cloth-01',
    type: 'cloth',
    x: 278,
    y: 358,
    width: 34,
    height: 20,
    rotation: '-10deg',
    visibleUntilStage: 1,
    zIndex: 69,
  },
  {
    id: 'mess-cloth-02',
    type: 'cloth',
    x: 452,
    y: 358,
    width: 26,
    height: 16,
    rotation: '15deg',
    visibleUntilStage: 2,
    zIndex: 69,
  },
  {
    id: 'mess-wrapper-01',
    type: 'wrapper',
    x: 328,
    y: 324,
    width: 18,
    height: 14,
    rotation: '8deg',
    visibleUntilStage: 1,
    zIndex: 69,
  },
];
