import type { IsometricCleaningMessItem } from '../types/isometricRoom';

export const isometricCleaningMessSafeArea = {
  minX: 150,
  maxX: 520,
  minY: 318,
  maxY: 432,
};

export const isometricCleaningMessItems: IsometricCleaningMessItem[] = [
  {
    id: 'mess-paper-01',
    type: 'paper',
    x: 218,
    y: 352,
    width: 18,
    height: 12,
    rotation: '-13deg',
    visibleUntilStage: 1,
    zIndex: 67,
  },
  {
    id: 'mess-paper-02',
    type: 'paper',
    x: 354,
    y: 390,
    width: 20,
    height: 13,
    rotation: '11deg',
    visibleUntilStage: 2,
    zIndex: 68,
  },
  {
    id: 'mess-paper-03',
    type: 'paper',
    x: 462,
    y: 338,
    width: 15,
    height: 11,
    rotation: '-6deg',
    visibleUntilStage: 3,
    zIndex: 68,
  },
  {
    id: 'mess-dust-01',
    type: 'dust',
    x: 176,
    y: 386,
    width: 28,
    height: 10,
    rotation: '-8deg',
    visibleUntilStage: 2,
    zIndex: 66,
  },
  {
    id: 'mess-dust-02',
    type: 'dust',
    x: 288,
    y: 414,
    width: 35,
    height: 12,
    rotation: '7deg',
    visibleUntilStage: 3,
    zIndex: 66,
  },
  {
    id: 'mess-dust-03',
    type: 'dust',
    x: 432,
    y: 400,
    width: 31,
    height: 11,
    rotation: '-5deg',
    visibleUntilStage: 2,
    zIndex: 66,
  },
  {
    id: 'mess-dust-04',
    type: 'dust',
    x: 506,
    y: 360,
    width: 26,
    height: 9,
    rotation: '13deg',
    visibleUntilStage: 1,
    zIndex: 66,
  },
  {
    id: 'mess-cloth-01',
    type: 'cloth',
    x: 266,
    y: 372,
    width: 34,
    height: 20,
    rotation: '-10deg',
    visibleUntilStage: 1,
    zIndex: 69,
  },
  {
    id: 'mess-cloth-02',
    type: 'cloth',
    x: 472,
    y: 372,
    width: 26,
    height: 16,
    rotation: '15deg',
    visibleUntilStage: 2,
    zIndex: 69,
  },
  {
    id: 'mess-wrapper-01',
    type: 'wrapper',
    x: 328,
    y: 334,
    width: 18,
    height: 14,
    rotation: '8deg',
    visibleUntilStage: 1,
    zIndex: 69,
  },
];
