import type { AchievementDefinition } from '@/features/achievements/types/achievement';

export const ACHIEVEMENT_DEFINITIONS: AchievementDefinition[] = [
  {
    id: 'first_xp',
    category: 'growth',
    title: '첫 성장',
    description: '처음으로 경험치 50을 쌓았어요.',
    rewardGrapes: 1,
    targetValue: 50,
    sortOrder: 1,
  },
  {
    id: 'steady_growth',
    category: 'growth',
    title: '꾸준한 성장',
    description: '누적 경험치 300을 달성했어요.',
    rewardGrapes: 3,
    targetValue: 300,
    sortOrder: 2,
  },
  {
    id: 'study_hours_10',
    category: 'study',
    title: '10시간 공부',
    description: '공부 시간이 10시간을 넘었어요.',
    rewardGrapes: 5,
    targetValue: 10,
    sortOrder: 3,
  },
  {
    id: 'study_hours_50',
    category: 'study',
    title: '50시간 공부',
    description: '공부 시간이 50시간을 넘었어요.',
    rewardGrapes: 10,
    targetValue: 50,
    sortOrder: 4,
  },
  {
    id: 'category_master',
    category: 'category',
    title: '카테고리 마스터',
    description: '한 카테고리 레벨 3을 달성했어요.',
    rewardGrapes: 8,
    targetValue: 3,
    sortOrder: 5,
  },
  {
    id: 'completion_streak',
    category: 'category',
    title: '반복의 힘',
    description: '같은 카테고리를 10회 이상 완료했어요.',
    rewardGrapes: 5,
    targetValue: 10,
    sortOrder: 6,
  },
  {
    id: 'grape_collector',
    category: 'reward',
    title: '포도 수집가',
    description: '포도 100개를 모았어요.',
    rewardGrapes: 10,
    targetValue: 100,
    sortOrder: 7,
  },
];
